spring:
  datasource:
    url: jdbc:postgresql:postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    schema:

---
spring:
  profiles: unittest
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:/create.sql

---
logging:
  level:
    org:
      hibernate: Info