# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.4.0"

BOX_NAME = "eventsourced-postgres"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.define BOX_NAME do |t| end
  config.vm.network :forwarded_port, host: 5432, guest: 5432

  config.vm.hostname = "#{BOX_NAME}.localdomain"
  config.vm.provider :virtualbox do |vbox|
    vbox.name = BOX_NAME
    vbox.memory = 1024
  end
  
  if Vagrant.has_plugin?("vagrant-proxyconf")
  	proxynameport = ENV['http_proxy'].to_s == ''? ENV['HTTP_PROXY']: ''

    if proxynameport.to_s != ''
      config.proxy.http     = "http://#{proxynameport}"
      config.proxy.https    = "https://#{proxynameport}"
      config.proxy.no_proxy = "localhost,127.0.0.1,/var/run/docker.sock"
    end
  end

  config.vm.provision :shell, :inline => "mkdir -p /var/lib/cloud/instance; touch /var/lib/cloud/instance/locale-check.skip"
  config.vm.provision :shell, :inline => "curl -sSL https://get.docker.com/ubuntu/ | sudo sh"
  config.vm.provision "docker", version: "1.5.0"
end

